apt.systemd.daily: fix error from locking code
Error:

    pkgs that look like they should be upgraded:
    Error in function stop
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/apt/progress/text.py", line 240,
    in stop
        apt_pkg.size_to_str(self.current_cps))).rstrip("\n"))
      File "/usr/lib/python3/dist-packages/apt/progress/text.py", line 51,
    in _write
        self._file.write("\r")
    AttributeError: 'NoneType' object has no attribute 'write'
    fetch.run() result: 0

Caused by:

    LOCKFD=3
    unattended_upgrades $LOCKFD>&-

Unfortunately this code does not work, it is equivalent to

    unattended_upgrades 3 >&-

I.e. it left fd 3 open, but closed stdout!

Closes: #862567
(cherry picked from commit 7b4581cbe8fcf6e2bd56a27c5a7a1e6ea33d2973)