Fix missing includes
This was missed in 4b22a1e36 (apt-team/apt!522), and caused the
following error when built with GCC 12:

    /var/tmp/apt-20251026-9687-pc954n/apt-3.1.10/apt-private/private-cmndline.cc:544:23: error: ‘optional’ is not a member of ‘std’
      544 | static std::pair<std::optional<long unsigned int>, std::optional<long unsigned int>> parseCliVersion(std::string_view version)
          |                       ^~~~~~~~
    /var/tmp/apt-20251026-9687-pc954n/apt-3.1.10/apt-private/private-cmndline.cc:27:8: note: ‘std::optional’ is defined in header ‘<optional>’; did you forget to ‘#include <optional>’?
       26 | #include <apti18n.h>
      +++ |+#include <optional>
       27 |                                                                         /*}}}*/

While at it, also add missing <utility> include for std::pair.

Discovered in https://github.com/Homebrew/homebrew-core/pull/251162 by
Anton Melnikov.

Co-authored-by: Anton Melnikov <antonsm21@gmail.com>
Signed-off-by: Ruoyu Zhong <zhongruoyu@outlook.com>